version: '2'
services:
  app:
    build: .
    command: bundle exec puma -C config/containers/puma.rb
    volumes:
      - /var/www/p_yam
    expose:
      - "3000"
    links:
      - mysql
      - redis

  mysql:
    image: mysql
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=xiaoliang
  redis:
    image: redis
    expose:
      - "6379"
  web:
    restart: always
    build:
      context: .
      dockerfile: config/containers/Dockerfile-nginx
    links:
      - app
    ports:
      - "81:80"
    volumes_from:
      - app