version: '2'
services:
  app:
    build: .
    command: bundle exec puma -C config/containers/puma.rb
    volumes:
      - /var/www/p_yam
    expose:
      - "3000"
    links:
      - mysql
      - redis
    env_file: 
      - ./config/containers/.env
  mysql:
    image: mysql
    ports:
      - "3306"
    env_file: 
      - ./config/containers/.env
  redis:
    image: redis
  web:
    restart: always
    build:
      context: .
      dockerfile: config/containers/Dockerfile-nginx
    links:
      - app
    ports:
      - "80:80"
    volumes_from:
      - app