defaults: &defaults
  yunpian:
    signature: "5fcc0e93908fb5e99ae70349d20e4451"
  qiniu:
    bucket: "chenxiyue"
  sendcloud: 
    uri: "http://api.sendcloud.net/apiv2/mail/send"
    api_user: "chengxiyue_test_Dv1H4N"
    api_key: "Sp8BSU0DV8XM1gUJ"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults